name: Validate with HACS

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac" # v4
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
