name: Validate with hassfest

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * *'

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac" # v4
        - uses: "home-assistant/actions/hassfest@master"
