name: Validate with hassfest

on:
  pull_request:
    branches:
      - main
    paths:
      - "custom_components/soma_connect/**"
      - "pyproject.toml"
      - "poetry.lock"
  schedule:
    - cron:  '0 0 * * *'

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - uses: "home-assistant/actions/hassfest@master"
