name: Validate with hassfest

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * *'

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608" # v4
        - uses: "home-assistant/actions/hassfest@master"
